### ISSUE TITLE
Sem notificação de inclusão de novo comentário

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/dadospessoais-tema#18]
O usuário Jorge Machado reportou que ao tentar realizar comentários no art 11 do apl de dados pessoais, não recebia a notificação de inclusão de novo comentário e, por isso, inclui uma série de comentários repetidos.

**Comment by diraol** [comment]
Vou avaliar como fornecer um feedback aos usuários.

**Comment by diraol** [comment]
Já havia sido feito, não achei o commit que resolve o problema.
